version: '3.8'

services:
  delivery-app:
    image: 'delivery:latest'
    build:
      context: .
    container_name: delivery-app
    depends_on:
      - delivery-db
      - delivery-kafka
    environment:
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_SCHEMAS=delivery
      - SPRING_FLYWAY_URL=jdbc:mysql://delivery-db:3306
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:mysql://delivery-db:3306/delivery?nullCatalogMeansCurrent=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL-AUTO=validate
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-app:8761/eureka
    ports:
      - '8080:8080'
    networks:
      - delivery-network
      - discovery-network

  delivery-db:
    image: 'mysql:latest'
    container_name: delivery-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    networks:
      - delivery-network

  delivery-kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: delivery-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=delivery-registry:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - delivery-registry
    networks:
      - delivery-network

  delivery-registry:
    image: 'confluentinc/cp-zookeeper:6.2.0'
    container_name: delivery-registry
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - delivery-network

networks:
  delivery-network:
  discovery-network:
    external:
      name: discovery-network
