version: '3.8'

services:
  app:
    image: 'delivery-management:latest'
    build:
      context: .
    container_name: delivery-management-app
    depends_on:
      - db
    environment:
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_SCHEMAS=delivery_management
      - SPRING_FLYWAY_URL=jdbc:mysql://db:3306
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/delivery_management?nullCatalogMeansCurrent=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - '8080:8080'

  db:
    image: 'mysql:latest'
    container_name: delivery-management-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
