server:
  port: 1921

spring:
  application.name: service-vehicle
  flyway:
    enabled: true
    schemas: vehicle
    url: ${spring.datasource.host}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  datasource:
    url: ${spring.datasource.host}/vehicle?nullCatalogMeansCurrent=true
    host: jdbc:mysql://localhost:3307
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
