spring:
  flyway:
    enabled: true
    schemas: delivery_management
    url: ${spring.datasource.host}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  datasource:
    url: ${spring.datasource.host}/delivery_management?nullCatalogMeansCurrent=true
    host: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
