server:
  port: 8080

spring:
  application.name: service-delivery
  flyway:
    enabled: true
    schemas: delivery
    url: ${spring.datasource.host}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: ${spring.datasource.host}/delivery?nullCatalogMeansCurrent=true
    host: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      topic:
        name: vehicle-fetch
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
